"""
03_analysis.py  —  H2 pipeline, the three models + auto-populated findings table

Model 1: Pearson + Spearman correlation, IV vs DV (full filtered sample)
Model 2: OLS  fundraising_efficiency ~ bank_branch_density + log_total_revenue
              + C(ntee_major) + C(region) + C(source_year) + poverty_rate + median_hh_income
Model 3: Model 2 re-run separately on mid ($500K-$2M) and large (>= $2M) subsamples

Writes findings_results.md with the populated Week-1 metrics table.
"""
import os
import numpy as np
import pandas as pd
from scipy import stats
import statsmodels.formula.api as smf

DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
HERE = os.path.dirname(os.path.abspath(__file__))


def iv_column(df):
    """Use density per-capita if ACS population was available, else raw branch count."""
    if df["bank_branch_density"].notna().sum() > 0.5 * len(df):
        return "bank_branch_density"
    print("[analysis] ACS population sparse — using raw branch count as IV.")
    return "bank_branch_density_raw"


def run_ols(df, iv, label):
    have_acs = df["poverty_rate"].notna().sum() > 0.5 * len(df)
    controls = "log_total_revenue + C(ntee_major) + C(region) + C(source_year)"
    if have_acs:
        controls += " + poverty_rate + median_hh_income"
    formula = f"fundraising_efficiency_w ~ {iv} + {controls}"
    m = smf.ols(formula, data=df).fit(cov_type="HC1")
    print(f"\n=== Model: {label}  (n={int(m.nobs):,}) ===")
    print(f"  IV coef ({iv}): beta={m.params[iv]:.5f}, "
          f"p={m.pvalues[iv]:.4g}, R2={m.rsquared:.4f}")
    return m


def main():
    df = pd.read_csv(os.path.join(DATA, "h2_modeling_frame.csv"))
    df = df.replace([np.inf, -np.inf], np.nan).dropna(subset=["fundraising_efficiency_w"])
    iv = iv_column(df)
    d = df.dropna(subset=[iv]).copy()

    # --- Model 1: correlation (level + log-log) ---
    pr, pp = stats.pearsonr(d[iv], d["fundraising_efficiency_w"])
    sr, sp = stats.spearmanr(d[iv], d["fundraising_efficiency_w"])
    print(f"\n=== Model 1 correlation (n={len(d):,}) ===")
    print(f"  [level] Pearson r={pr:.4f} (p={pp:.4g}) | Spearman rho={sr:.4f} (p={sp:.4g})")

    # log-log Pearson — the valid statistic on these log-normal variables.
    log_iv = f"log_{iv}"
    lpr = lpp = float("nan")
    if log_iv in d.columns and "log_fundraising_efficiency" in d.columns:
        dl = d.dropna(subset=[log_iv, "log_fundraising_efficiency"])
        lpr, lpp = stats.pearsonr(dl[log_iv], dl["log_fundraising_efficiency"])
        print(f"  [log-log] Pearson r={lpr:.4f} (p={lpp:.4g})  <-- valid linear measure")

    # --- Threshold check: efficiency by IV quartile (catches non-linearity) ---
    print("\n=== Density-quartile means (threshold/non-linearity check) ===")
    dq = d.copy()
    dq["iv_quartile"] = pd.qcut(dq[iv], 4, labels=["Q1_low", "Q2", "Q3", "Q4_high"],
                                duplicates="drop")
    qtab = dq.groupby("iv_quartile", observed=True)["fundraising_efficiency_w"].agg(
        ["count", "mean", "median"])
    print(qtab.round(2).to_string())

    # --- Model 2: full OLS ---
    m2 = run_ols(d, iv, "Model 2 — full filtered sample")

    # --- Model 3: by size segment ---
    mods = {}
    for seg in ("mid", "large"):
        sub = d[d["size_segment"] == seg]
        if len(sub) > 50:
            mods[seg] = run_ols(sub, iv, f"Model 3 — {seg}")

    # --- populate the Week-1 findings table ---
    fe = d["fundraising_efficiency_w"]
    mid_n = int((d["size_segment"] == "mid").sum())
    large_n = int((d["size_segment"] == "large").sum())
    lines = [
        "# H2 Findings — Week 1 Results\n",
        f"_Auto-generated by 03_analysis.py · n={len(d):,}_\n",
        "| Metric | Value |",
        "|---|---|",
        f"| Total orgs after revenue filter (>=$500K) | {len(df):,} |",
        f"| Orgs in modeling frame (non-zero fundraising spend) | {len(d):,} |",
        f"| Mid-size orgs ($500K-$2M) | {mid_n:,} |",
        f"| Large orgs (>=$2M) | {large_n:,} |",
        f"| IV used | `{iv}` |",
        f"| Mean bank-branch density | {d[iv].mean():.4f} ± {d[iv].std():.4f} |",
        f"| Mean fundraising efficiency | {fe.mean():.3f} ± {fe.std():.3f} |",
        f"| Pearson r — level (Model 1) | r={pr:.4f}, p={pp:.4g} |",
        f"| Pearson r — log-log (Model 1, valid) | r={lpr:.4f}, p={lpp:.4g} |",
        f"| Spearman rho (Model 1) | rho={sr:.4f}, p={sp:.4g} |",
        f"| OLS beta on IV (Model 2) | {m2.params[iv]:.5f} "
        f"(95% CI {m2.conf_int().loc[iv,0]:.5f}, {m2.conf_int().loc[iv,1]:.5f}), "
        f"p={m2.pvalues[iv]:.4g} |",
        f"| R-squared (Model 2) | {m2.rsquared:.4f} |",
    ]
    for seg, m in mods.items():
        lines.append(f"| OLS beta on IV ({seg}, Model 3) | {m.params[iv]:.5f}, "
                     f"p={m.pvalues[iv]:.4g}, R2={m.rsquared:.4f} |")

    # density-quartile means (threshold / non-linearity check)
    lines += ["", "## Fundraising efficiency by bank-branch-density quartile",
              "| IV quartile | n | mean efficiency | median efficiency |",
              "|---|---|---|---|"]
    for q, row in qtab.iterrows():
        lines.append(f"| {q} | {int(row['count']):,} | {row['mean']:.2f} | {row['median']:.2f} |")

    out = os.path.join(HERE, "findings_results.md")
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"\n[analysis] findings table written -> {out}")


if __name__ == "__main__":
    main()
